### ISSUE TITLE
Car Axis

### ISSUE THREAD

**Issue by AlexBins** [AlexBins/EvoTest#4]
@ManuelMende Ich bin mir nicht sicher, ob es sich wirklich lohnt, die Axen vernünftig zu legen. Der Code funktioniert gerade und ich würde ihn wirklich ungern anfassen... Sofern es dir nicht wirklich wichtig ist, wäre ich deswegen dafür, diesen Branch wieder zu schließen.

**Comment by ManuelMende** [comment]
@AlexBins: Ich denke es wäre sauberer, mit dem tatsächlichem Fahrmodell zu arbeiten. Hast du den PA mit dem echten Fahrzeug schon getestet? Ich werde mich da heute mal dran setzen.

**Comment by ManuelMende** [comment]
Ich habe jetzt mal den **Master in den CarAxis** branch gemerged und mir das **ganze angesehen**. Wenn die **Parklücke ausreichend groß** ist,** funktioniert der Parkvorgang**, so wie ich das sehe. Ihr könnt euch das ganze ja mal anschauen (habe den *CarAxis* Branch auf den aktuellen Stand gesetzt).

**Comment by ManuelMende** [comment]
Also ich nehme an wir lassen die richtige Physik weg?

**Comment by AlexBins** [comment]
Ich hab mir das jetzt nochmal angeschaut, und festgestellt, dass es wirklich sehr schwer ist direkt umzusetzen. Unser Ansatz bisher hat nämlich so gar nicht vollkommen funktioniert.
Müssen wir also meiner Meinung nach leider wirklich fallen lassen.

**Comment by ManuelMende** [comment]
Dann wird das Thema hiermit geschlossen. Ist den Aufwand nicht wert.
