### ISSUE TITLE
Multipopulations-Algorithmus

### ISSUE THREAD

**Issue by ManuelMende** [AlexBins/EvoTest#7]
# Problemstellung

Wir benötigen ein Framework um:

- mehrere Populationen zu verwalten
- mehrere Genetische Algorithmen (Instanzen) zu verwalten
- Einen genetischen Algorithmus mit einer bekannten Population weiter laufen zu lassen
- Eine Möglichkeit zum Austausch von Individuen

# Lösungsansatz

- Zusammenfassen von Individuen in einer Populationsklasse `Population`
- Erweitern der GA-implementierung um:
        - Individuen einer Population zu tauschen
        - An beliebiger Stelle weiter zu machen
- Formulieren einer Überklasse `MultiPopulation` (übernimmt das Tauschen der Individuen)

Des Weiteren müssen wir unsere Testfall-Klassen formulieren, und die entsprechenden Fitnessfunktionen zusammenbauen.

# Fragestellung
Ich schlage vor wir verwenden dieses Issue als Diskussionsplattform, um ein Konzept auszuarbeiten.

**Comment by ManuelMende** [comment]
Ich habe die entsprechenden Klasse auf den Branch `multiPopulationGA` veröffentlicht.

**Comment by AlexBins** [comment]
Bevor wir hier weiter machen, habe ich mich auch n bisschen mit strukturellem befasst und n bisschen refactored.

**1. Cromosome -> Chromosome
2. Fitnes -> Fitness**

Das ist natürlich auch für den weiteren Verlauf nicht unwichtig, deswegen seid ihr hier auch beide verlinkt.
@ManuelMende @ydirey

**Comment by AlexBins** [comment]
Vorschlag Population:```

Chromosome[] chromosomes
integer size
Konstruktor:
Population(integer size)

```
Offene Fragen:
Soll die Möglichkeit bestehen, Chromosome indiziert nach Fitnesswert abzufragen (index 1 => bestes Chromosom). Das passt sehr gut zum Migrationsproblem.

**Comment by AlexBins** [comment]
Vorschlag GeneticAlgorithm:
```
Population Population
Integer Epoch
Number ReproductionRate

number FitnessFunction(Chromosome)
Chromosome SelectCandidateFunction(Chromosome[])
Chromosome MergeFunction(Chromosome, Chromosome)
Chromosome MutateFunction(Chromosome)

ctor GeneticAlgorithm(Integer population_size, Integer epoch, Number reproduction_rate,
         handle fitness_function, handle selection_function, handle merge_function,
         handle mutation_function)

void RunEpoch()

```
Hier hat sich eigentlich gar nicht viel geändert.
Die Population wurde natürlich ausgelagert, aber sonst sind die Properties gleich.
Der Konstruktor ist unberührt.
AddToPopulation und ReducePopulation wurden ebenfalls ausgelagert.

Die größte Änderung wird vermutlich sein, dass wir jetzt die Parallelität (beziehungsweise eher die simulierte Parallelität) beachten müssen. Ich habe keine Erfahrung mit Matlab parallel programming und würde persönlich auch wirklich gerne drauf verzichten. Ist jetzt schon schwer genug zu debuggen.
Deswegen würde ich sagen, die MPGA Instanz soll den Takt angeben, und jeweils eine Epoche eines jeden sub-GAs nach der anderen berechnen. Deswegen die Methode RunEpoch.

**Comment by ManuelMende** [comment]
1. `Reduce` sollte evntl ein entsprechendes handle übergeben bekommen, welches verwendet wird
2. Der GA wird nur mit handles initialisiert. `RunEpoch` verändert dann die Population, die als Parameter übergeben wurde
3. Parallelität erstmal gerne pseudoparalell 
4. MPGA sollte wirklich die interpopulationaoperationen ausführen

Das wäre meine Meinung dazu.

**Comment by AlexBins** [comment]
Vorschlag MultiPopulationGA:

```
GeneticAlgorithm[] GeneticAlgorithms
Number MigrationRate
Integer PopulationSize
Integer Epoch

ctor MultiPopulationGA(Number migration_rate, Integer population_size)

void AddGeneticAlgorithm(handle fitness_func, handle initialize_func, [handle selector_func],
             [handle merge_func], [handle mutator_func])
void RunEpoch()
void Run([termination criterium | Integer epoch_number])
```

**Comment by AlexBins** [comment]
> ```Reduce``` sollte evntl ein entsprechendes handle übergeben bekommen, welches verwendet wird
Hier würde ich jetzt persönlich erst mal widersprechen, da es sich bei diesem Reduce nicht um eine Aktion zwischen den GAs handelt, sondern innerhalb eines jeden einzelnen GAs. Das ist das Reduce, das wir bisher auch schon nutzen. Deswegen stimme ich dir in deiner Aussage zu, dass wir MPGA alles interpopulationäre übernehmen lassen sollen, allerdings handelt es sich bei Reduce nicht um so etwas.

> MPGA sollte wirklich die interpopulationaoperationen ausführen
Siehe oben.

> Parallelität erstmal gerne pseudoparalell
👍

> Der GA wird nur mit handles initialisiert. RunEpoch verändert dann die Population, die als Parameter übergeben wurde

Das klingt immer besser, je länger ich darüber nachdenke. Auch wenn es ein wenig mehr Umabu erfordert

**Comment by ManuelMende** [comment]
# Bzgl Reduce
Das ist doch eine Operation auf der `Population`, hat mit der MPGA Implementierung nichts zu tun. Hier werden unerwünschte Chromosomen entfernt. **Wie sollen diese ausgewählt werden?**

# bzgl ReproductionRate
Passt so weit, das ist ein sinnvoller Parameter für den GA

**Comment by AlexBins** [comment]
Einfach die unfittesten rausschmeißen.
Halte ich nicht für nötig, dafür 'n function handle einzuführen.

**Comment by AlexBins** [comment]
Zur Vorgehensweise:
Da wir je Population vollkommen unabhängig einzelne Testfälle betrachten, halte ich es nicht für sinnvoll, ziwschen den einzelnen Populationen zu migrieren.
In der Ergebnispopulation muss hingegen darauf geachtet werden, dass nicht einzelne Testfälle anderen vorgezogen werden, sonst werden die migrierten Chromosome aus den entsprechend "schlechten" Testfällen sofort wieder aussortiert. Alternativ können wir natürlich auch argumentieren, dass es durchaus sinnvoll ist, manche Testfälle anderen vorzuziehen.

Da wir allerdings für jeden Testfall einzeln eine Fitnessfunktion erstellen müssen, wäre ich dafür, dass wir an diesen arbeiten. Hier ist folgendes auf jeden Fall zu tun:
1. Preprocessing einführen: Bevor wir anfangen, die Fitness auszuwerten, muss das Szenario ein mal ausgeführt werden. Das sollte nicht bei jeder Ausführung durchgeführt werden, wenn wir Fitnessfunktionen miteinander multiplizieren.

2. Wir brauchen bessere Fitnessfunktionen. Unter anderem müssen wir Kollisionen besser bewerten. Hierzu hätte ich zumindest folgenden Vorschlag:
Bewerte Kollisionen schlecht (Faktor = -1), wenn sie vor dem eintreten in die Parklücke auftreten. Bewerte sie gut, wenn sie nach dem Eintreten in die Parklücke auftreten (Faktor = 1). Evt mittels Berechnung des Abstandes vom Auto zur Parklücke (d): Faktor / (d + 1). Diese Formel würde bewirken, dass für jede Kollision INNERHALB der Parklücke 1 als Fitness errechnet wird und für alle außerhalb ein etwas kleinerer Wert. Diesen Wert kann man dann einfach auf die andere Fitness multiplizieren. Diese Funktion erstetzt allerdings NICHT den Plausibilitätscheck, da der GA das Auto auch einfach in der Parklücke in eine Wand setzen kann.

**Comment by ManuelMende** [comment]
## Migration
> In der Ergebnispopulation muss hingegen darauf geachtet werden, dass nicht einzelne Testfälle anderen vorgezogen werden

Du möchtest also im letzten Durchlauf schon migrieren, obwohl es an sich nicht sinnvoll ist?

> (Er hat ja auch gesagt, da sollen wir überlegen, was für uns am sinnvollsten ist)

Ja, aber vllt schauen wir trotzdem mal, ob uns das was bringt.

## Fitness
Definitiv müssen wir verschiedene Funktionen aufbauen. Dein Ansatz klingt gut.

**Comment by AlexBins** [comment]
Migration: So wie ich das verstanden hatte, sollten wir doch zb alle x Iterationen zwischen den Populationen migrieren, oder?
Wir haben n-1 Testfall-Arten in den ersten n-1 Populationen. Ich persönlich würde aus diesen n-1 Populationen jeweils direkt in die n-te Population migrieren. Auf dieser sollte allerdings eine Fitnessfunktion benutzt werden, die keine bestimmten Arten von Testfällen bevorzieht. Das ist alles, was ich meinte...
Ich bin mir nich ganz sicher, ob ich damit das Konzept von MPGA vollständig erfasst hab, aber ich dachte, das trifft es durchaus...
Immerhin soll auch auf der n-ten Population ein GA laufen, oder?
Auch wenn diese Population ständig von anderen gefüttert wird.

**Comment by ManuelMende** [comment]
Ja letztendlich passt das schon. Trotzdem denke ich, dass zwischendurch Migration auch sinnvoll ist. Im Zweifel fliegen die Migranten schnell raus.

In den anderen Populationen bleiben sie ja enthalten. Und wir wollen ja nur TCs die für die Population auch geeignet sind.

**Comment by ManuelMende** [comment]
> In Add wird der Fitness Wert des neuen Chromosomes berechnet.

Das ist aber schwierig, weil `Population` ja eigentlich nur die Chromosome hält und nicht weiß, zu welchem GA und damit zu welcher Fitnessfunktion sie gehört!

## Lösungsvorschlag
Der GA berechnet die Fitness und schreibt sie in das Chromosome. 

## Problem
Man muss zum einen vor der Iteration die Fitness der Population für den entsprechenden GA anpassen, als auch vor dem Aufruf der `reduce`-Funktion. Damit kommt es u.U. zu einem doppelten Aufruf der Fitnessfunktion.

Mein Aktueller Ansatz:
- Vor `reduce` die Fitness-Funktion
- `runEpoch` setzt voraus, dass die Fitnesswerte der Population zur Fitnessfunktion des GA 

:+1: / :-1: ?
